name: Gold Price Auto Updater
on:
  schedule:
    - cron: '*/1 * * * *' # รันทุก 10 นาทีอัตโนมัติ
  workflow_dispatch: # กดรันเองด้วยมือได้จากหน้า GitHub

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install axios firebase-admin
      - run: node updater.js
